import { User, Coins, Gift, Package } from 'lucide-react';

export const slides = [
    {
        id: 1,
        headline: 'BEST ACCOUNTS, BEST DEALS',
        subtext: 'Get premium accounts at unbeatable prices. Start playing instantly!',
        ctaText: 'Shop Accounts',
        ctaLink: '/services/accounts',
        accentColor: 'from-orange-600 to-orange-400',
        icon: User,
        image: '/pages-backgrounds/valorant-bg-1.png',
        bgColor: 'from-black via-gray-900 to-black',
        origins: ['valorant', 'gtav', 'fortnite', 'lol', 'osrs', 'roblox'],
    },
    {
        id: 2,
        headline: 'LEVEL UP WITH GAME CURRENCY',
        subtext: 'Buy game currency at the lowest prices and power up your progress!',
        ctaText: 'Buy Currency',
        ctaLink: '/services/currency',
        accentColor: 'from-orange-600 to-orange-400',
        icon: Coins,
        image: '/pages-backgrounds/gtav-bg-1.png',
        bgColor: 'from-black via-gray-900 to-black',
        origins: ['gtav', 'fortnite', 'lol', 'osrs', 'pokemon-go'],
    },
    {
        id: 3,
        headline: 'GIFT CARDS FOR EVERY GAMER',
        subtext: 'PlayStation, Xbox, Steam & more — all in one place.',
        ctaText: 'Get Gift Cards',
        ctaLink: '/services/giftcards',
        accentColor: 'from-orange-600 to-orange-400',
        icon: Gift,
        image: '/pages-backgrounds/fortnite-bg.jpg',
        bgColor: 'from-black via-gray-900 to-black',
        origins: ['fortnite', 'roblox', 'clash'],
    },
    {
        id: 4,
        headline: 'RARE IN-GAME ITEMS',
        subtext: 'Unlock rare skins, weapons, and more — instantly delivered.',
        ctaText: 'Browse Items',
        ctaLink: '/services/items',
        accentColor: 'from-orange-600 to-orange-400',
        icon: Package,
        image: '/pages-backgrounds/lol-bg.png',
        bgColor: 'from-black via-gray-900 to-black',
        origins: ['lol', 'valorant', 'osrs', 'clash'],
    },
];
